[server]
headless = true
port = 8501
enableCORS = false

[theme]
primaryColor="#1abc9c"
backgroundColor="#f0f2f6"
secondaryBackgroundColor="#ffffff"
textColor="#000000"
font="sans serif"

[global]
showErrorDetails = true

[browser]
gatherUsageStats = false
